name: Push Docker Image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to push the Docker image'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    name: Build and Push Docker Image to ${{ github.event.inputs.environment }} Environment
    environment: ${{ github.event.inputs.environment }}
    runs-on: namespace-profile-docuum
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-actions-platform-api
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: Dockerfile
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/docuum:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/docuum:latest
